# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug')),
                ('html', models.TextField(blank=True, verbose_name='HTML')),
                ('template', models.CharField(blank=True, help_text='Enter a template to be rendered. If field TEMPLATE is given, the content of field HTML will be passed as template variable {{ html }} to the template. Otherwise, the content of field HTML is rendered.', max_length=255, verbose_name='Template')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
            },
        ),
        migrations.CreateModel(
            name='ChunkPtr',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_chunks_chunkptr', serialize=False, to='cms.CMSPlugin')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_chunks.Chunk')),
            ],
            options={
                'verbose_name': 'Chunk Ptr',
                'verbose_name_plural': 'Chunk Ptrs',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_chunks.Chunk', verbose_name='Chunk')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
    ]
