# Generated by Django 2.2.12 on 2020-05-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_chunks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangocms_chunks.Chunk', verbose_name='Chunk'),
        ),
    ]
